name: "Setup Python Dependencies"
description: "Setup Python environment and install dependencies from lockfile"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.x"
  requirements-file:
    description: "Path to requirements file"
    required: false
    default: "requirements-lock.txt"
  upgrade-pip:
    description: "Upgrade pip before installing requirements"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: ${{ inputs.requirements-file }}

    - name: Upgrade pip
      if: inputs.upgrade-pip == 'true'
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install Python packages
      shell: bash
      run: python -m pip install -r ${{ inputs.requirements-file }}
