# Anolis Runtime Configuration
# Phase 4: HTTP Gateway + Basic provider config

runtime:
  mode: MANUAL  # Always MANUAL in v0

http:
  enabled: true
  bind: 127.0.0.1
  port: 8080

providers:
  - id: sim0
    command: D:/repos_feast/anolis-provider-sim/build/Release/anolis-provider-sim.exe
    args: []
    timeout_ms: 5000

polling:
  interval_ms: 500  # Default polling interval (min 100ms)

telemetry:
  enabled: false

automation:
  enabled: false  # Set to true to enable behavior tree automation
  behavior_tree: ./behaviors/demo.xml
  tick_rate_hz: 10  # 1-1000 Hz

logging:
  level: info  # debug, info, warn, error
