# Anolis Runtime Configuration with Telemetry
# InfluxDB Telemetry enabled
#
# PREREQUISITES:
#   1. Start InfluxDB + Grafana:
#      cd tools/docker && docker-compose -f docker-compose.observability.yml up -d
#   2. Set INFLUXDB_TOKEN environment variable OR use token below
#
# DASHBOARDS:
#   - Open http://localhost:3000 (admin/anolis123)
#   - Navigate to Dashboards → Signal History or Device Health

runtime:
  name: "anolis-telemetry"      # Instance identifier
  shutdown_timeout_ms: 2000     # Provider graceful shutdown timeout (500-30000ms)
  startup_timeout_ms: 30000     # Overall startup timeout (5000-300000ms)

http:
  enabled: true
  bind: 127.0.0.1
  port: 8080

providers:
  - id: sim0
    # Portable relative path (adjust based on your build configuration)
    # Windows Release: ../anolis-provider-sim/build/Release/anolis-provider-sim.exe
    # Windows Debug:   ../anolis-provider-sim/build/Debug/anolis-provider-sim.exe
    # Linux/macOS:     ../anolis-provider-sim/build/anolis-provider-sim
    command: ../anolis-provider-sim/build/Release/anolis-provider-sim
    args: ["--config", "../anolis-provider-sim/config/provider-sim.yaml"]
    timeout_ms: 5000

polling:
  interval_ms: 500

telemetry:
  enabled: true
  influxdb:
    url: http://localhost:8086
    org: anolis
    bucket: anolis
    token: dev-token # Or set INFLUXDB_TOKEN env var
    batch_size: 100 # Flush batch when this size reached
    flush_interval_ms: 1000 # Flush every second

logging:
  level: info
