# Anolis Runtime Configuration
# HTTP Gateway + Basic provider config

runtime:
  mode: MANUAL # Always MANUAL in v0

http:
  enabled: true
  bind: 127.0.0.1
  port: 8080

providers:
  - id: sim0
    command: D:/repos_feast/anolis-provider-sim/build/Release/anolis-provider-sim.exe
    args: []
    timeout_ms: 5000

polling:
  interval_ms: 500 # Default polling interval (min 100ms)

telemetry:
  enabled: true
  influx_url: http://localhost:8086
  influx_org: anolis
  influx_bucket: anolis
  influx_token: dev-token
  batch_size: 100
  flush_interval_ms: 1000
  queue_size: 10000

automation:
  enabled: true # Set to true to enable behavior tree automation
  behavior_tree: ./behaviors/demo.xml
  tick_rate_hz: 10 # 1-1000 Hz
  manual_gating_policy: BLOCK # BLOCK or OVERRIDE

  # Runtime parameters
  parameters:
    - name: temp_setpoint
      type: double
      default: 25.0
      min: 10.0
      max: 50.0

    - name: motor_duty_cycle
      type: int64
      default: 50
      min: 0
      max: 100

    - name: control_enabled
      type: bool
      default: true

    - name: operating_mode
      type: string
      default: "normal"
      allowed_values: ["normal", "test", "emergency"]

logging:
  level: info # debug, info, warn, error
