name: "Validate Lockfile"
description: "Validates requirements-lock.txt encoding and integrity"
inputs:
  lockfile-path:
    description: "Path to requirements-lock.txt"
    required: false
    default: "requirements-lock.txt"
runs:
  using: "composite"
  steps:
    - name: Validate lockfile encoding
      shell: bash
      run: |
        LOCKFILE="${{ inputs.lockfile-path }}"

        if [ ! -f "$LOCKFILE" ]; then
          echo "ERROR: $LOCKFILE not found" >&2
          exit 1
        fi

        # Check for NUL bytes (binary corruption) using od
        if od -An -tx1 "$LOCKFILE" | tr -d ' \n' | grep -q 00; then
        echo "OK: $LOCKFILE is valid UTF-8 and contains no NUL bytes"
