name: "Run CTest with Summary"
description: "Execute CTest and generate GitHub Actions summary"
inputs:
  build-dir:
    description: "CMake build directory"
    required: false
    default: "build"
  config:
    description: "Build configuration (Release, Debug, RelWithDebInfo)"
    required: false
    default: "Release"
  test-name:
    description: "Test suite name for summary"
    required: true
  platform:
    description: "Platform name for summary"
    required: false
    default: "Linux"
  timeout:
    description: "Test timeout in seconds"
    required: false
    default: "300"
  log-file:
    description: "Output log filename"
    required: false
    default: "ctest-output.log"
outputs:
  exit-code:
    description: "CTest exit code"
    value: ${{ steps.run-tests.outputs.exit-code }}
  total-tests:
    description: "Total number of tests"
    value: ${{ steps.run-tests.outputs.total }}
  passed-tests:
    description: "Number of passed tests"
    value: ${{ steps.run-tests.outputs.passed }}
  failed-tests:
    description: "Number of failed tests"
    value: ${{ steps.run-tests.outputs.failed }}
runs:
  using: "composite"
  steps:
    - name: Run CTest
      id: run-tests
      shell: bash
      run: |
        set +e
        set -o pipefail
        echo "=== Running CTest ==="
        ctest --test-dir ${{ inputs.build-dir }} \
              --output-on-failure \
              --timeout ${{ inputs.timeout }} \
              -C ${{ inputs.config }} 2>&1 | tee ${{ inputs.log-file }}
        CTEST_EXIT=${PIPESTATUS[0]}

        # Parse test results
        TOTAL_TESTS=$(grep -oP '\d+(?= tests?)' ${{ inputs.log-file }} | tail -1 || echo "0")
        PASSED_TESTS=$(grep -oP '\d+(?= tests? passed)' ${{ inputs.log-file }} | tail -1 || echo "0")
        FAILED_TESTS=$(grep -oP '\d+(?= tests? failed)' ${{ inputs.log-file }} | tail -1 || echo "0")

        # Set outputs
        echo "exit-code=$CTEST_EXIT" >> $GITHUB_OUTPUT
        echo "total=$TOTAL_TESTS" >> $GITHUB_OUTPUT
        echo "passed=$PASSED_TESTS" >> $GITHUB_OUTPUT
        echo "failed=$FAILED_TESTS" >> $GITHUB_OUTPUT

        # Generate summary
        {
          echo "## ${{ inputs.test-name }} (${{ inputs.platform }})"
          echo ""
          if [ $CTEST_EXIT -eq 0 ]; then
            echo "**PASS:** All tests passed ✅"
          else
            echo "**FAIL:** Tests failed ❌"
          fi
          echo ""
          echo "- **Total:** $TOTAL_TESTS"
          echo "- **Passed:** $PASSED_TESTS"
          echo "- **Failed:** $FAILED_TESTS"
          echo ""
        } >> $GITHUB_STEP_SUMMARY

        exit $CTEST_EXIT
