name: "Check Sanitizer Logs"
description: "Check for sanitizer reports and generate summary"
inputs:
  sanitizer-type:
    description: "Sanitizer type (ASAN, UBSAN, TSAN, LSAN)"
    required: true
  log-pattern:
    description: "Glob pattern for log files (e.g., asan.*, tsan.*)"
    required: true
  test-phase:
    description: "Test phase name (e.g., Unit Tests, Integration Tests)"
    required: true
  max-reports:
    description: "Maximum number of report lines to display"
    required: false
    default: "50"
outputs:
  issues-found:
    description: "Whether issues were detected"
    value: ${{ steps.check.outputs.issues-found }}
  issue-count:
    description: "Number of issue files found"
    value: ${{ steps.check.outputs.count }}
runs:
  using: "composite"
  steps:
    - name: Check for sanitizer reports
      id: check
      shell: bash
      run: |
        set +e

        # Check if sanitizer log files exist
        if ls ${{ inputs.log-pattern }} 1>/dev/null 2>&1; then
          ISSUE_COUNT=$(ls ${{ inputs.log-pattern }} 2>/dev/null | wc -l)
          echo "issues-found=true" >> $GITHUB_OUTPUT
          echo "count=$ISSUE_COUNT" >> $GITHUB_OUTPUT
          
          {
            echo "## ${{ inputs.sanitizer-type }} ${{ inputs.test-phase }} - Issues Detected ⚠️"
            echo ""
            echo "**Issues found:** $ISSUE_COUNT"
            echo ""
            echo "### First Issue Report:"
            echo '```'
            head -100 ${{ inputs.log-pattern }} 2>/dev/null | head -${{ inputs.max-reports }}
            echo '```'
            echo ""
            echo "See artifacts for full reports."
          } >> $GITHUB_STEP_SUMMARY
          
          exit 1
        else
          echo "issues-found=false" >> $GITHUB_OUTPUT
          echo "count=0" >> $GITHUB_OUTPUT
          
          {
            echo "## ${{ inputs.sanitizer-type }} ${{ inputs.test-phase }} Passed ✅"
            echo ""
            echo "- No issues detected"
            echo "- All tests passed successfully"
          } >> $GITHUB_STEP_SUMMARY
          
          exit 0
        fi
