name: "Checkout anolis-provider-sim"
description: "Checkout anolis-provider-sim repository with recursive submodules"
inputs:
  path:
    description: "Path to checkout anolis-provider-sim"
    required: false
    default: "anolis-provider-sim"
runs:
  using: "composite"
  steps:
    - name: Checkout anolis-provider-sim
      uses: actions/checkout@v4
      with:
        repository: FEASTorg/anolis-provider-sim
        path: ${{ inputs.path }}
        submodules: recursive
