{
 "title": "Signal History",
 "tags": [
  "anolis",
  "signals"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "Data Source", "query": "influxdb" },
   {
    "name": "provider_id",
    "label": "Provider",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"anolis\", tag: \"provider_id\")"
   },
   {
    "name": "device_id",
    "label": "Device",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"anolis\", tag: \"device_id\")"
   },
   {
    "name": "signal_id",
    "label": "Signal",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"anolis\", tag: \"signal_id\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Signal Values (Double)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"anolis\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anolis_signal\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value_double\")\n  |> filter(fn: (r) => r[\"provider_id\"] =~ /${provider_id:regex}/)\n  |> filter(fn: (r) => r[\"device_id\"] =~ /${device_id:regex}/)\n  |> filter(fn: (r) => r[\"signal_id\"] =~ /${signal_id:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Signal Values (Boolean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"anolis\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anolis_signal\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value_bool\")\n  |> filter(fn: (r) => r[\"provider_id\"] =~ /${provider_id:regex}/)\n  |> filter(fn: (r) => r[\"device_id\"] =~ /${device_id:regex}/)\n  |> map(fn: (r) => ({ r with _value: if r._value then 1 else 0 }))\n  |> yield(name: \"bool\")"
    }
   ]
  },
  {
   "title": "Signal Values (Integer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"anolis\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anolis_signal\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value_int\")\n  |> filter(fn: (r) => r[\"provider_id\"] =~ /${provider_id:regex}/)\n  |> filter(fn: (r) => r[\"device_id\"] =~ /${device_id:regex}/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}