name: "Setup vcpkg"
description: "Configure vcpkg package manager with specified commit"
inputs:
  vcpkg-commit:
    description: "vcpkg git commit hash to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ inputs.vcpkg-commit }}
        doNotCache: false
